# Generated by Django 4.2.4 on 2023-08-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chapitre', '0003_chapitre_contenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('chapitres', models.ManyToManyField(blank=True, related_name='chapitres', to='chapitre.chapitre')),
            ],
        ),
    ]
