# Generated by Django 4.2.4 on 2023-08-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matiere', '0001_initial'),
        ('niveau', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='niveau',
            name='chapitres',
        ),
        migrations.AddField(
            model_name='niveau',
            name='matieres',
            field=models.ManyToManyField(blank=True, related_name='matieres_niveau', to='matiere.matiere'),
        ),
    ]
