# Generated by Django 4.1.10 on 2023-09-12 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapitre', '0006_rename_skills_skill'),
        ('cours', '0002_cours_chapitre'),
    ]

    operations = [
        migrations.CreateModel(
            name='SousSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.TextField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chapitre.skill')),
            ],
        ),
    ]
