# Generated by Django 4.2.4 on 2023-08-30 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chapitre', '0003_chapitre_contenu'),
        ('niveau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('chapitres', models.ManyToManyField(blank=True, related_name='chapitress', to='chapitre.chapitre')),
                ('niveau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='niveau', to='niveau.niveau')),
            ],
        ),
    ]
