# Generated by Django 4.2.4 on 2023-08-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapitre', '0002_chapitre_student_chapitre_teacher_score_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitre',
            name='contenu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
