# Generated by Django 4.2.4 on 2023-09-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapitre', '0002_chapitre_student_chapitre_teacher_score_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitre',
            name='joint_file',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
