# Generated by Django 4.2.4 on 2023-08-30 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matiere', '0001_initial'),
        ('user', '0001_initial'),
        ('chapitre', '0003_chapitre_contenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitre',
            name='matieree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matiere', to='matiere.matiere'),
        ),
        migrations.AlterField(
            model_name='chapitre',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapitre_creé', to='user.userclass'),
        ),
    ]
