# Generated by Django 4.1.10 on 2023-09-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapitre', '0004_chapitre_matiere_delete_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.TextField()),
                ('niveau', models.IntegerField(default=6)),
                ('matiere', models.TextField(default='رياضبات')),
            ],
        ),
    ]
