# Generated by Django 4.1.10 on 2023-09-12 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapitre', '0005_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
