# Generated by Django 4.1.10 on 2023-09-12 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('quiz', '0002_quiz_cours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='cours',
        ),
        migrations.AddField(
            model_name='quiz',
            name='skill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='skills.sousskill'),
            preserve_default=False,
        ),
    ]
