# Generated by Django 4.1.10 on 2023-09-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_quiz_cours_quiz_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='choix',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='response',
            field=models.CharField(max_length=200),
        ),
    ]
