# Generated by Django 4.1.10 on 2023-09-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_quiz_choix_alter_quiz_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='response',
            field=models.TextField(),
        ),
    ]
